![Logo del Instituto](img/logoitqv1.jpg)

# 0.1 01MIAR- Estructuras de datos, +Pandas

![Logo de Python](img/python_logo.png)

* Nombre: Alejandra López
* Fecha: **10-07-2026**
* Repositorio: <a href="https://github.com/Alelop-Itu/machine12026nocturno.git"> Link del repositorio de Github</a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

## 1 Operaciones en pandas
**Búsqueda**

In [4]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  4  0  1
1  0  5  5

In [5]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [6]:
 # buscando valores
display(frame.isin([3,2])) #--> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False  False  False
1  False  False  False

In [7]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

1

       A      B      C
0   True  False  False
1  False  False  False

[[ True False False]
 [False False False]]

numpy.ndarray

In [8]:
 # Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

3

       A      B      C
0   True  False  False
1  False   True   True

**Ordenación**

In [10]:
from random import shuffle
rand_matrix = np.random.randint(20,size=(5,4))
indices = list(range(5))
shuffle(indices) # mezcla indices
frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D   A   C   B
2  11   3  10   9
4   3  19  10   3
3  17   1   8  10
1  14  13  15   1
0   7   8   6  18

In [11]:
 # ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4   3  19  10   3
3  17   1   8  10
2  11   3  10   9
1  14  13  15   1
0   7   8   6  18

    D   A   C   B
2  11   3  10   9
4   3  19  10   3
3  17   1   8  10
1  14  13  15   1
0   7   8   6  18

In [14]:
 #ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
2  11  10   9   3
4   3  10   3  19
3  17   8  10   1
1  14  15   1  13
0   7   6  18   8

In [16]:
 # ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
3  17   1   8  10
2  11   3  10   9
0   7   8   6  18
1  14  13  15   1
4   3  19  10   3

In [17]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    B   A   D   C
2   9   3  11  10
4   3  19   3  10
3  10   1  17   8
1   1  13  14  15
0  18   8   7   6

In [18]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
4   3  19  10   3
1  14  13  15   1
0   7   8   6  18
2  11   3  10   9
3  17   1   8  10

In [19]:
#filtrado con np.where
distances = pd.Series([12.1,np.nan,12.8,76.9,6.1,7.2])
valid_distances = np.where(pd.notnull(distances),distances,2)
print(valid_distances)
print(type(valid_distances))

[12.1  2.  12.8 76.9  6.1  7.2]
<class 'numpy.ndarray'>

## Ranking
* Construir un ranking de valores

In [20]:
display(frame)

    D   A   C   B
4   3  19  10   3
1  14  13  15   1
0   7   8   6  18
2  11   3  10   9
3  17   1   8  10

In [21]:
 display(frame.rank(method='max', axis=1))

     D    A    C    B
4  2.0  4.0  3.0  2.0
1  3.0  2.0  4.0  1.0
0  2.0  3.0  1.0  4.0
2  4.0  1.0  3.0  2.0
3  4.0  1.0  2.0  3.0

In [23]:
 # Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

15
10
10
8
6

## 2 Operaciones
Operaciones matemáticas entre objetos

In [25]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  39  21  41  40
1  37  82   8  74
2   1  27  98  21
3  18  48  13  12

    0   1   2   3
0  53  80  14  56
1  40  44  63  59
2  85  94  89  57
3  27  18   1  21

In [26]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0    1    2    3
0  92  101   55   96
1  77  126   71  133
2  86  121  187   78
3  45   66   14   33

In [27]:
display(frameB- frameA == frameB.sub(frameA))
display(frameB- frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0  14  59 -27  16
1   3 -38  55 -15
2  84  67  -9  36
3   9 -30 -12   9

In [28]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  39  21  41  40
1  37  82   8  74
2   1  27  98  21
3  18  48  13  12

    0   1   2
0   6  71  17
1  16  10  73
2  97  53  12

      0     1      2   3
0  45.0  92.0   58.0 NaN
1  53.0  92.0   81.0 NaN
2  98.0  80.0  110.0 NaN
3   NaN   NaN    NaN NaN

In [29]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

      0     1      2     3
0  45.0  92.0   58.0  40.0
1  53.0  92.0   81.0  74.0
2  98.0  80.0  110.0  21.0
3  18.0  48.0   13.0  12.0

Operadores aritméticos solo válidos en elementos aceptables

In [33]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA- frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [34]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)
display(df.iloc[0])
display(type(df.iloc[0]))

# uso común, averiguar la diferencia entre una fila y el resto
display(df- df.iloc[0])
display(df.sub(df.iloc[0], axis=1))

# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  2  6  8  4
1  3  9  2  9
2  2  8  0  4

A    2
B    6
C    8
D    4
Name: 0, dtype: int32

pandas.core.series.Series

   A  B  C  D
0  0  0  0  0
1  1  3 -6  5
2  0  2 -8  0

   A  B  C  D
0  0  0  0  0
1  1  3 -6  5
2  0  2 -8  0

   A  B  C  D
0  0  4  6  2
1  0  6 -1  6
2  0  6 -2  2

pandas se basa en NumPy, np operadores binarios y unarios son aceptables

| Tipo | Operación | Descripción |
|:---------|:-----|:------- |
| Unario | abs |  Valor absoluto de cada elemento  |
|  | sqrt | Raíz cuadrada de cada elemento      |
|  | exp | Raíz cuadrada de cada elemento      |
|  | log, log10, log2 |Logaritmos en distintas bases de cada elemento      |
|  | sign | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo)  |
|  | ceil | Redondea cada elemento por arriba  |
|   | floor | Redondea cada elemento por abajo   |
|  | isnan |  Retorna si cada elemento es Nan |
|  |cos, sin, tan| Operaciones trigonométricas en cada elemento|
|  | arccos, arcsin, arctan  | Inversas de operaciones trigonométricas en cada elemento  |
| Binario | add| Suma de dos arrays  |
|  | substract|  Resta de dos arrays |
|  | multiply| Multiplicación de dos arrays  |
|  | divide | División de dos arrays  |
|  | maximum, minimum | Retorna el valor máximo/mínimo de cada pareja de elementos  |
|  |equal, not_equal |  Retorna la comparación (igual o no igual) de cada pareja de elementos |
|  | greater, greater_equal,n |  Retorna la comparación(>, >=, <, <= respectivamente) de cada pareja de elementos
 |
|  | less, less_equal |   |


Aplicación de funciones a medida con lambda

In [36]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max()- x.min(), axis = 1)) # diferencia por columna

   A  B  C  D
0  1  6  6  5
1  5  2  3  6
2  4  4  3  7

0    5
1    4
2    4
dtype: int64

In [37]:
def max_min(x):
    return x.max()- x.min()
print(frame.apply(max_min, axis = 0)) # diferencia por columna

A    4
B    4
C    3
D    2
dtype: int64

In [38]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max()- x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  4  0  3  4
1  1  6  3  0
2  0  2  8  5

0    4
1    6
2    8
dtype: int64

## 3 Estadística descriptiva
* Análisis preliminar de los datos
* Para Series y DataFrame

Operación | Descripción |
|:-----|:------- |
| count | Número de valores no NaN  |
| describe | Conjunto de estadísticas sumarias  |
| min, max | Valores mínimo y máximo  |
| argminm, argmax | Índices posicionales del valor mínimo y máximo  |
| idxmin, idxmax | Índices semánticos del valor mínimo y máximo  |
| sum | Suma de los elementos  |
| mean | Media de los elementos  |
| median | Mediana de los elementos  |
| mad | Desviación absoluta media del valor medio  |
| var | Varianza de los elementos |
| std | Desviación estándar de los elementos  |
| cumsum | Suma acumulada de los elementos  |
| diff | Diferencia aritmética de los elementos |

In [40]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30],
"puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [41]:
 # operadores básicos
print(frame.sum())
display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [43]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [44]:
 frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [45]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [46]:
print(frame['edad'].std())

10.996211468804457

In [47]:
frame['edad'].idxmax()

0

In [48]:
frame['puntos'].idxmin()

1

In [49]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [50]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [51]:
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

## 3.1 Agregaciones

In [52]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [53]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [54]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [55]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [56]:
 # funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean','max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [57]:
 # Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
    return x["edad"].mean() > 30
display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

## 3.2 Correlaciones
pandas incluye métodos para analizar correlaciones
  * Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación) - obj.corr(obj2) > medida de correlación entre los datos de ambos objetos- https://blogs.oracle.com/ai-and datascience/post/introduction-to-correlation

### 3.2.1 Ejemplo Fuel efficiency
* https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [59]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
mpg_data = pd.read_csv(path, sep='\s+', header=None,
names = ['mpg', 'cilindros', 'desplazamiento','potencia',
'peso', 'aceleracion', 'año', 'origen', 'nombre'],
na_values='?', engine='c')

In [60]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
147,24.0,4,90.0,75.0,2108.0,15.5,74,2,fiat 128
287,16.5,8,351.0,138.0,3955.0,13.2,79,1,mercury grand marquis
261,18.1,6,258.0,120.0,3410.0,15.1,78,1,amc concord d/l
210,19.0,6,156.0,108.0,2930.0,15.5,76,3,toyota mark ii
279,29.5,4,98.0,68.0,2135.0,16.6,78,3,honda accord lx

In [61]:
 display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [62]:
 mpg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 28.1+ KB

### 3.2.2 Correlaciones entre valores

In [64]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg =- peso

np.float64(-0.8317409332443351)

In [65]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso =- aceleracion

np.float64(-0.4174573199403932)

### 3.2.3 Correlaciones entre todos los valores

In [66]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [67]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [70]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [ ]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [ ]:
 # correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

In [ ]:
 # correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax() ␣
↪#consigo misma....

In [ ]:
 # tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

In [ ]:
 positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1,␣
↪vmin=-1.0, vmax=1.0)

In [57]:
# indexar por posición con 'iloc'
print(df_data.iloc[0]) # --> Series de la primera fila (qué marca los índices)

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [58]:
# indexar semántico con 'loc'
df_data.loc['a'] # --> Series de la fila con índice 'a'

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [59]:
# indexar semántico con 'loc'
df_data.loc[:'b'] # --> DataFrame de la fila con índice 'a' y 'b'

      ciudad  temperatura   o2  humedad  co2
a   Valencia           10  1.0      NaN  NaN
b  Barcelona            8  NaN      NaN  NaN

In [60]:
df_data.loc[:'b'].loc[:,["o2", "humedad"]] # slicing anidado

    o2  humedad
a  1.0      NaN
b  NaN      NaN

In [62]:
# si se modifica una porcion del dataframe se modifica el dataframe original (referencia)
display(df_data)
serie = df_data.loc['a']
print(serie)
serie.iloc[2] = 3000 # setting with copy warning!!!
display(df_data)

# copiar data frame
df_2 = df_data.loc['a'].copy()
df_2.iloc[2] = 3000
display(df_2)
display(df_data)

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

C:\Users\ALEJANDRA\AppData\Local\Temp\ipykernel_26348\1651117478.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  serie.iloc[2] = 3000 # setting with copy warning!!!

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

ciudad         Valencia
temperatura          10
o2                 3000
humedad             NaN
co2                 NaN
Name: a, dtype: object

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

In [63]:
# ambos aceptan 'axis' como argumento
# df_data.iloc(axis=1)[0] # --> todos los valores asignados a la primera columna 'ciudad'
df_data.loc(axis=1)['ciudad'] # --> equivalente frame['ciudad']

a     Valencia
b    Barcelona
c     Valencia
d       Madrid
e      Sevilla
f     Valencia
Name: ciudad, dtype: object

In [64]:
 # qué problema puede tener este fragmento?
frame = pd.DataFrame({"Name" : ['Carlos','Pedro'], "Age" : [34,22]},index=[1,0])
display(frame)

     Name  Age
1  Carlos   34
0   Pedro   22

In [65]:
# por defecto, pandas interpreta índice posicional --> error en frames
# cuando hay posible ambigüedad, utilizar loc y iloc
print('Primera fila\n')
print(frame.iloc[0])
print('\nElemento con index 0\n')
print(frame.loc[0])

Primera fila

Name    Carlos
Age         34
Name: 1, dtype: object

Elemento con index 0

Name    Pedro
Age        22
Name: 0, dtype: object

## 4.4 Objeto Index de Pandas

In [66]:
# Contrucción de índices
ind = pd.Index([2, 3, 5, 23, 26])
# recuperar datos
print(ind[3])
print(ind[::2])

23
Index([2, 5, 26], dtype='int64')

In [67]:
# usar un objeto index al crear dataframe
frame = pd.DataFrame({"Name" : ['Carlos','Pedro', 'Manolo', 'Luis', 'Alberto'], "Age" : [34,22,15,55,23]}, index=ind)
display(frame)

       Name  Age
2    Carlos   34
3     Pedro   22
5    Manolo   15
23     Luis   55
26  Alberto   23

In [68]:
# Son inmutables! No se modifican los datos.
ind[3] = 8

TypeError: Index does not support mutable operations

In [70]:
# change index column
frame = pd.DataFrame({"Name" : ['Carlos','Pedro', 'Manolo', 'Luis', 'Alberto'],"Age" : [34,22,15,55,23]}, index=ind)
display(frame)
frame.set_index('Age', inplace=True)
display(frame)

       Name  Age
2    Carlos   34
3     Pedro   22
5    Manolo   15
23     Luis   55
26  Alberto   23

        Name
Age
34    Carlos
22     Pedro
15    Manolo
55      Luis
23   Alberto

## 4.5 Slicing

In [72]:
 # slice por filas
d_and_d_characters = {'Name' : ['bundenth','theorin','barlok'], 'Strength' : [10,12,19], 'Wisdom' : [20,13,6]}
character_data = pd.DataFrame(d_and_d_characters, index=['a','b','c'])
display(character_data)
display(character_data[:-1])
display(character_data[1:2])

       Name  Strength  Wisdom
a  bundenth        10      20
b   theorin        12      13
c    barlok        19       6

       Name  Strength  Wisdom
a  bundenth        10      20
b   theorin        12      13

      Name  Strength  Wisdom
b  theorin        12      13

In [73]:
# slicing para columnas
display(character_data[['Name','Wisdom']])

       Name  Wisdom
a  bundenth      20
b   theorin      13
c    barlok       6

In [74]:
 #slicing con 'loc' e 'iloc'
display(character_data.iloc[1:])
display(character_data.loc[:'b','Name':'Strength'])

      Name  Strength  Wisdom
b  theorin        12      13
c   barlok        19       6

       Name  Strength
a  bundenth        10
b   theorin        12

¿Cómo filtrar filas y columnas? Por ejemplo, para todos los personajes, obtener ‘Name’ y ‘Strength’

In [75]:
# usando 'loc' para hacer slicing
display(character_data.loc[:,'Name':'Strength'])

       Name  Strength
a  bundenth        10
b   theorin        12
c    barlok        19

In [76]:
# usando 'loc' para buscar específicamente filas y columnas
display(character_data.loc[ ['a','c'], ['Name','Wisdom'] ])

       Name  Wisdom
a  bundenth      20
c    barlok       6

In [77]:
# lo mismo con 'iloc'?
display(character_data.iloc[[0,2],[0,2]])
display(character_data.iloc[[0,-1],[0,-1]])

       Name  Wisdom
a  bundenth      20
c    barlok       6

       Name  Wisdom
a  bundenth      20
c    barlok       6

In [79]:
# lista de los personajes con el atributo Strength > 11
display(character_data.loc[character_data['Strength'] > 11, ['Name','Strength']])

      Name  Strength
b  theorin        12
c   barlok        19

In [81]:
# listar los personajes con Strength > 15 o Wisdom > 15
display(character_data.loc[(character_data['Strength'] > 15) | (character_data['Wisdom'] > 15)])

       Name  Strength  Wisdom
a  bundenth        10      20
c    barlok        19       6

## 5 Cargar y guardar datos en pandas

In [84]:
# Guardar a csv
import os
ruta = os.path.join("res" ,"o_d_d_characters.csv")
#character_data.to_csv(ruta, sep=';') # sep por defecto: ','

In [85]:
loaded = pd.read_csv(ruta, sep=';')
display(loaded)

  Unnamed: 0      Name  Strength  Wisdom
0          a  bundenth        10      20
1          b   theorin        12      13
2          c    barlok        19       6

In [86]:
ruta = os.path.join("res","titanic.csv")

In [87]:
titanic = pd.read_csv(ruta, sep=',')
display(titanic)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [89]:
loaded = pd.read_csv(ruta, sep=',', index_col = 0)
display(loaded)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q


**otros argumentos to_csv()**
* na_rep=‘string’ –> representar valores NaN en el archivo csv


**otros argumentos read_csv()**
* na_values=‘string’

Pandas también ofrece funciones para leer/guardar a otros formatos estándares: JSON, HDF5 o
Excel en su ([API](https://pandas.pydata.org/pandas-docs/stable/reference/io.html)).

# 6 Ejemplo práctico en pandas
* MovieLens dataset
* Reviews de películas
* 1 millón de entradas
* Datos demográficos de usuarios

In [91]:
import numpy as np
import pandas as pd
import zipfile # para descomprimir archivos zip
import urllib.request # para descargar de URL
import os

# descargar MovieLens dataset
url = 'http://files.grouplens.org/datasets/movielens/ml-1m.zip'
ruta = os.path.join("res", "ml-1m.zip")
urllib.request.urlretrieve(url, ruta)

('res\\ml-1m.zip', <http.client.HTTPMessage at 0x2a6a19938a0>)

In [94]:
# descomprimiendo archivo zip
ruta_ext = os.path.join("res")
with zipfile.ZipFile(ruta, 'r') as z:
    print('Extracting all files...')
    z.extractall(ruta_ext) # destino
    print('Done!')
# take a look at readme y revisar formatos

Extracting all files...
Done!

In [95]:
ruta_users = os.path.join("res", "ml-1m", "users.dat")
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0, engine='python')
display(users_dataset)

      F  1.1  10  48067
1
2     M   56  16  70072
3     M   25  15  55117
4     M   45   7  02460
5     M   25  20  55455
6     F   50   9  55117
...  ..  ...  ..    ...
6036  F   25  15  32603
6037  F   45   1  76006
6038  F   56   1  14706
6039  F   45   0  01060
6040  M   25   6  11106

[6039 rows x 4 columns]

In [96]:
# Varios problemas
# sin cabecera! primer valor se ha perdido
# las columnas no tienen nombres
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names: if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
  Column(s) to use as row label(s), denoted either by column labels or column
  indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
  will be formed for the row labels.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g., when you have a malformed file with delimiters at
  the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion.

    .. versionadded:: 1.5.0

        Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
        the default determines the ``dtype`` of the columns which are not explicitly
        listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The 'pyarrow' engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
    per-column ``NA`` values.  By default the following values are interpreted as
    ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
    "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
    "n/a", "nan", "null ".

keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
verbose : bool, default False
    Indicate number of ``NA`` values placed in non-numeric columns.

    .. deprecated:: 2.2.0
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
      ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
    * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.
    * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
      as a single date column. Values are joined with a space before parsing.
    * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
      result 'foo'. Values are joined with a space before parsing.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
    format of the ``datetime`` strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has no effect.

keep_date_col : bool, default False
    If ``True`` and ``parse_dates`` specifies combining multiple columns then
    keep the original columns.
date_parser : Callable, optional
    Function to use for converting a sequence of string columns to an array of
    ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. pandas will try to call ``date_parser`` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by ``parse_dates`` into a single array
    and pass that; and 3) call ``date_parser`` once for each row using one or
    more strings (corresponding to the columns defined by ``parse_dates``) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`~pandas.to_datetime` as-needed.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates when used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
        time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
        and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
    characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
   When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

    .. versionadded:: 1.4.0

        - Callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine='python'``

    .. versionchanged:: 2.2.0

        - Callable, function with signature
          as described in `pyarrow documentation
          <https://arrow.apache.org/docs/python/generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_ when ``engine='pyarrow'``

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be

In [98]:
# especificar nombres, cargar sin cabecera
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],engine='python')
display(users_dataset)

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460
5           M   25          20    55455
...       ...  ...         ...      ...
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

[6040 rows x 4 columns]

In [99]:
# samplear la tabla
display(users_dataset.sample(10))

       Gender  Age  Occupation Zip-code
UserID
3700        M   25          14    10021
2968        F   18           0    48104
4788        M   35           7    85331
1075        F   25           6    60660
4840        F   45           6    63135
4530        F   35           1    92103
3613        M   25           0    37205
2759        M   25           7    36102
5774        M   18           4    94118
888         F    1          10    08820

In [100]:
# samplear la cabeza
display(users_dataset.head(4))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460

In [101]:
# samplear la cola
display(users_dataset.tail(10))

       Gender  Age  Occupation Zip-code
UserID
6031        F   18           0    45123
6032        M   45           7    55108
6033        M   50          13    78232
6034        M   25          14    94117
6035        F   25           1    78734
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

In [102]:
# tipos de datos sobre las columnas
users_dataset.dtypes

Gender        object
Age            int64
Occupation     int64
Zip-code      object
dtype: object

In [103]:
display(users_dataset[users_dataset['Zip-code'].str.len() > 5])

       Gender  Age  Occupation    Zip-code
UserID
161         M   45          16  98107-2117
233         F   45          20  37919-4204
293         M   56           1  55337-4056
458         M   50          16  55405-2546
506         M   25          16  55103-1006
...       ...  ...         ...         ...
5682        M   18           0  23455-4959
5904        F   45          12      954025
5925        F   25           0  90035-4444
5967        M   50          16  73069-5429
5985        F   18           4  78705-5221

[81 rows x 4 columns]

In [104]:
# información general sobre atributos numéricos
display(users_dataset.describe())

               Age   Occupation
count  6040.000000  6040.000000
mean     30.639238     8.146854
std      12.895962     6.329511
min       1.000000     0.000000
25%      25.000000     3.000000
50%      25.000000     7.000000
75%      35.000000    14.000000
max      56.000000    20.000000

In [105]:
 users_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6040 entries, 1 to 6040
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      6040 non-null   object
 1   Age         6040 non-null   int64
 2   Occupation  6040 non-null   int64
 3   Zip-code    6040 non-null   object
dtypes: int64(2), object(2)
memory usage: 235.9+ KB

In [106]:
# incluir otros atributos (no todo tiene sentido)
display(users_dataset.describe(include='all'))

       Gender          Age   Occupation Zip-code
count    6040  6040.000000  6040.000000     6040
unique      2          NaN          NaN     3439
top         M          NaN          NaN    48104
freq     4331          NaN          NaN       19
mean      NaN    30.639238     8.146854      NaN
std       NaN    12.895962     6.329511      NaN
min       NaN     1.000000     0.000000      NaN
25%       NaN    25.000000     3.000000      NaN
50%       NaN    25.000000     7.000000      NaN
75%       NaN    35.000000    14.000000      NaN
max       NaN    56.000000    20.000000      NaN

In [107]:
# cuántos usuarios son mujeres (Gender='F')
len(users_dataset[users_dataset['Gender'] == 'F'])
#select count(*) from users_dataset where users_dataset.Gender = 'F'

1709

In [108]:
# mostrar solo los menores de edad
under_age = users_dataset[users_dataset['Age'] == 1]
print(len(under_age))
display(under_age.sample(10))

222

       Gender  Age  Occupation Zip-code
UserID
4135        M    1          10    46321
2003        M    1          10    80014
888         F    1          10    08820
1           F    1          10    48067
1327        M    1          10    12159
2189        M    1          10    60148
2806        M    1          10    15208
1563        F    1          10    87123
1154        F    1          10    53545
1348        F    1          10    04240

In [109]:
# filtrar edad incorrecta (míninimo 18) SettingWithCopyWarning!!!
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'], engine='python')
under_age = users_dataset[users_dataset['Age'] == 1]
under_age.loc['Age'] = np.nan
display(under_age.head())
# users_dataset[users_dataset['Age'] < 18] = under_age
# display(users_dataset)

C:\Users\ALEJANDRA\AppData\Local\Temp\ipykernel_26348\4263585071.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  under_age.loc['Age'] = np.nan

       Gender  Age  Occupation Zip-code
UserID
1           F  1.0        10.0    48067
19          M  1.0        10.0    48073
51          F  1.0        10.0    10562
75          F  1.0        10.0    01748
86          F  1.0        10.0    54467

In [111]:
# filtrar edad incorrecta (míninimo 18) Fixing it by Copying the slice
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'], engine='python')
under_age = users_dataset[users_dataset['Age'] == 1]
under_age_copy = under_age.copy()
display(under_age_copy.head())
under_age_copy['Age'] = np.nan
display(under_age_copy.head())
users_dataset[users_dataset['Age'] == 1] = under_age_copy # sets the rows according to the indexes
display(users_dataset.head())

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
19          M    1          10    48073
51          F    1          10    10562
75          F    1          10    01748
86          F    1          10    54467

       Gender  Age  Occupation Zip-code
UserID
1           F  NaN          10    48067
19          M  NaN          10    48073
51          F  NaN          10    10562
75          F  NaN          10    01748
86          F  NaN          10    54467

       Gender   Age  Occupation Zip-code
UserID
1           F   NaN          10    48067
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455

In [113]:
# filtrar edad incorrecta (míninimo 18) Remove them from the dataset
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'], engine='python')
display(users_dataset[users_dataset['Age'] == 1].head(4))
users_dataset.loc[users_dataset['Age'] == 1, 'Age'] = np.nan
display(users_dataset)
display(users_dataset.loc[pd.isnull(users_dataset['Age'])].head(4))
users_dataset.drop(users_dataset[pd.isnull(users_dataset['Age'])].index, inplace = True)
display(users_dataset.head(4))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
19          M    1          10    48073
51          F    1          10    10562
75          F    1          10    01748

       Gender   Age  Occupation Zip-code
UserID
1           F   NaN          10    48067
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455
...       ...   ...         ...      ...
6036        F  25.0          15    32603
6037        F  45.0           1    76006
6038        F  56.0           1    14706
6039        F  45.0           0    01060
6040        M  25.0           6    11106

[6040 rows x 4 columns]

       Gender  Age  Occupation Zip-code
UserID
1           F  NaN          10    48067
19          M  NaN          10    48073
51          F  NaN          10    10562
75          F  NaN          10    01748

       Gender   Age  Occupation Zip-code
UserID
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455

In [114]:
# Agrupar datos por atributos
display(users_dataset.groupby(by='Gender').describe())
# Grabar la tabla modificada
# Cambiar el separador a ','
# Guardar NaN como 'null'
ruta_output = os.path.join('res', 'ml-1m', 'o_users_processed.csv')
users_dataset.to_csv(ruta_output, sep=',',na_rep='null')

           Age                                                     Occupation  \
         count       mean        std   min   25%   50%   75%   max      count
Gender
F       1631.0  32.287554  11.792015  18.0  25.0  25.0  45.0  56.0     1631.0
M       4187.0  31.568665  11.716053  18.0  25.0  25.0  35.0  56.0     4187.0


            mean       std  min  25%  50%   75%   max
Gender
F       6.498467  5.960285  0.0  1.0  4.0  11.0  20.0
M       8.743253  6.441753  0.0  4.0  7.0  15.0  20.0

# 7 Ejercicios
* Hacer un análisis general de los otros dos archivos CSV en ml-1m (‘movies.dat’ y ‘ratings.dat’)
* Analizando el dataset ratings.dat, ¿hay algún usuario que no tenga ninguna review? ¿Cuántos
tienen menos de 30 reviews?

In [117]:
# especificar nombres, cargar sin cabecera
import os
import pandas as pd
ruta_ratings = os.path.join("res", "ml-1m", "ratings.dat")
ratings_dataset = pd.read_csv(ruta_ratings, sep='::',
header=None, names=['UserID','MovieID','Rating','Timestamp'], engine='python')
display(ratings_dataset)

         UserID  MovieID  Rating  Timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [120]:
 # hay algún usuario que no tenga ninguna review
n_users_with_reviews = len(ratings_dataset.groupby(by='UserID'))
print(n_users_with_reviews)
n_users = len(users_dataset)
print(n_users)
print(n_users - n_users_with_reviews)

6040
5818
-222

In [121]:
# Cuántos tienen menos de 30 reviews
ratings_under_30 = ratings_dataset.groupby(['UserID'])['UserID'].filter(lambda␣x: len(x) < 30).value_counts()
display(ratings_under_30)
print(len(ratings_under_30)

SyntaxError: invalid character '␣' (U+2423) (3306539196.py, line 2)