![Logo del Instituto](https://raw.githubusercontent.com/Alelop-Itu/machine12026nocturno/refs/heads/main/img/logoitqv1.jpg)

# 0.1 01MIAR- Estructuras de datos, +Pandas

![Logo de Python](https://raw.githubusercontent.com/Alelop-Itu/machine12026nocturno/refs/heads/main/img/python_logo.png)

* Nombre: Alejandra López
* Fecha: **10-07-2026**
* Repositorio: <a href="https://github.com/Alelop-Itu/machine12026nocturno.git"> Link del repositorio de Github</a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

## 1 Operaciones en pandas
**Búsqueda**

In [4]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  4  0  1
1  0  5  5

In [5]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [6]:
 # buscando valores
display(frame.isin([3,2])) #--> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False  False  False
1  False  False  False

In [7]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

1

       A      B      C
0   True  False  False
1  False  False  False

[[ True False False]
 [False False False]]

numpy.ndarray

In [8]:
 # Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

3

       A      B      C
0   True  False  False
1  False   True   True

**Ordenación**

In [10]:
from random import shuffle
rand_matrix = np.random.randint(20,size=(5,4))
indices = list(range(5))
shuffle(indices) # mezcla indices
frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D   A   C   B
2  11   3  10   9
4   3  19  10   3
3  17   1   8  10
1  14  13  15   1
0   7   8   6  18

In [11]:
 # ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4   3  19  10   3
3  17   1   8  10
2  11   3  10   9
1  14  13  15   1
0   7   8   6  18

    D   A   C   B
2  11   3  10   9
4   3  19  10   3
3  17   1   8  10
1  14  13  15   1
0   7   8   6  18

In [14]:
 #ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
2  11  10   9   3
4   3  10   3  19
3  17   8  10   1
1  14  15   1  13
0   7   6  18   8

In [16]:
 # ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
3  17   1   8  10
2  11   3  10   9
0   7   8   6  18
1  14  13  15   1
4   3  19  10   3

In [17]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    B   A   D   C
2   9   3  11  10
4   3  19   3  10
3  10   1  17   8
1   1  13  14  15
0  18   8   7   6

In [18]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
4   3  19  10   3
1  14  13  15   1
0   7   8   6  18
2  11   3  10   9
3  17   1   8  10

In [19]:
#filtrado con np.where
distances = pd.Series([12.1,np.nan,12.8,76.9,6.1,7.2])
valid_distances = np.where(pd.notnull(distances),distances,2)
print(valid_distances)
print(type(valid_distances))

[12.1  2.  12.8 76.9  6.1  7.2]
<class 'numpy.ndarray'>

## Ranking
* Construir un ranking de valores

In [20]:
display(frame)

    D   A   C   B
4   3  19  10   3
1  14  13  15   1
0   7   8   6  18
2  11   3  10   9
3  17   1   8  10

In [21]:
 display(frame.rank(method='max', axis=1))

     D    A    C    B
4  2.0  4.0  3.0  2.0
1  3.0  2.0  4.0  1.0
0  2.0  3.0  1.0  4.0
2  4.0  1.0  3.0  2.0
3  4.0  1.0  2.0  3.0

In [23]:
 # Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

15
10
10
8
6

## 2 Operaciones
Operaciones matemáticas entre objetos

In [25]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  39  21  41  40
1  37  82   8  74
2   1  27  98  21
3  18  48  13  12

    0   1   2   3
0  53  80  14  56
1  40  44  63  59
2  85  94  89  57
3  27  18   1  21

In [26]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0    1    2    3
0  92  101   55   96
1  77  126   71  133
2  86  121  187   78
3  45   66   14   33

In [27]:
display(frameB- frameA == frameB.sub(frameA))
display(frameB- frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0  14  59 -27  16
1   3 -38  55 -15
2  84  67  -9  36
3   9 -30 -12   9

In [28]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  39  21  41  40
1  37  82   8  74
2   1  27  98  21
3  18  48  13  12

    0   1   2
0   6  71  17
1  16  10  73
2  97  53  12

      0     1      2   3
0  45.0  92.0   58.0 NaN
1  53.0  92.0   81.0 NaN
2  98.0  80.0  110.0 NaN
3   NaN   NaN    NaN NaN

In [29]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

      0     1      2     3
0  45.0  92.0   58.0  40.0
1  53.0  92.0   81.0  74.0
2  98.0  80.0  110.0  21.0
3  18.0  48.0   13.0  12.0

Operadores aritméticos solo válidos en elementos aceptables

In [33]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA- frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [34]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)
display(df.iloc[0])
display(type(df.iloc[0]))

# uso común, averiguar la diferencia entre una fila y el resto
display(df- df.iloc[0])
display(df.sub(df.iloc[0], axis=1))

# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  2  6  8  4
1  3  9  2  9
2  2  8  0  4

A    2
B    6
C    8
D    4
Name: 0, dtype: int32

pandas.core.series.Series

   A  B  C  D
0  0  0  0  0
1  1  3 -6  5
2  0  2 -8  0

   A  B  C  D
0  0  0  0  0
1  1  3 -6  5
2  0  2 -8  0

   A  B  C  D
0  0  4  6  2
1  0  6 -1  6
2  0  6 -2  2

pandas se basa en NumPy, np operadores binarios y unarios son aceptables

| Tipo | Operación | Descripción |
|:---------|:-----|:------- |
| Unario | abs |  Valor absoluto de cada elemento  |
|  | sqrt | Raíz cuadrada de cada elemento      |
|  | exp | Raíz cuadrada de cada elemento      |
|  | log, log10, log2 |Logaritmos en distintas bases de cada elemento      |
|  | sign | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo)  |
|  | ceil | Redondea cada elemento por arriba  |
|   | floor | Redondea cada elemento por abajo   |
|  | isnan |  Retorna si cada elemento es Nan |
|  |cos, sin, tan| Operaciones trigonométricas en cada elemento|
|  | arccos, arcsin, arctan  | Inversas de operaciones trigonométricas en cada elemento  |
| Binario | add| Suma de dos arrays  |
|  | substract|  Resta de dos arrays |
|  | multiply| Multiplicación de dos arrays  |
|  | divide | División de dos arrays  |
|  | maximum, minimum | Retorna el valor máximo/mínimo de cada pareja de elementos  |
|  |equal, not_equal |  Retorna la comparación (igual o no igual) de cada pareja de elementos |
|  | greater, greater_equal,n |  Retorna la comparación(>, >=, <, <= respectivamente) de cada pareja de elementos
 |
|  | less, less_equal |   |


Aplicación de funciones a medida con lambda

In [36]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max()- x.min(), axis = 1)) # diferencia por columna

   A  B  C  D
0  1  6  6  5
1  5  2  3  6
2  4  4  3  7

0    5
1    4
2    4
dtype: int64

In [37]:
def max_min(x):
    return x.max()- x.min()
print(frame.apply(max_min, axis = 0)) # diferencia por columna

A    4
B    4
C    3
D    2
dtype: int64

In [38]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max()- x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  4  0  3  4
1  1  6  3  0
2  0  2  8  5

0    4
1    6
2    8
dtype: int64

## 3 Estadística descriptiva
* Análisis preliminar de los datos
* Para Series y DataFrame

Operación | Descripción |
|:-----|:------- |
| count | Número de valores no NaN  |
| describe | Conjunto de estadísticas sumarias  |
| min, max | Valores mínimo y máximo  |
| argminm, argmax | Índices posicionales del valor mínimo y máximo  |
| idxmin, idxmax | Índices semánticos del valor mínimo y máximo  |
| sum | Suma de los elementos  |
| mean | Media de los elementos  |
| median | Mediana de los elementos  |
| mad | Desviación absoluta media del valor medio  |
| var | Varianza de los elementos |
| std | Desviación estándar de los elementos  |
| cumsum | Suma acumulada de los elementos  |
| diff | Diferencia aritmética de los elementos |

In [40]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30],
"puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [41]:
 # operadores básicos
print(frame.sum())
display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [43]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [44]:
 frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [45]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [46]:
print(frame['edad'].std())

10.996211468804457

In [47]:
frame['edad'].idxmax()

0

In [48]:
frame['puntos'].idxmin()

1

In [49]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [50]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [51]:
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

## 3.1 Agregaciones

In [52]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [53]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [54]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [55]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [56]:
 # funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean','max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [57]:
 # Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
    return x["edad"].mean() > 30
display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

## 3.2 Correlaciones
pandas incluye métodos para analizar correlaciones
  * Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación) - obj.corr(obj2) > medida de correlación entre los datos de ambos objetos- https://blogs.oracle.com/ai-and datascience/post/introduction-to-correlation

### 3.2.1 Ejemplo Fuel efficiency
* https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [59]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
mpg_data = pd.read_csv(path, sep='\s+', header=None,
names = ['mpg', 'cilindros', 'desplazamiento','potencia',
'peso', 'aceleracion', 'año', 'origen', 'nombre'],
na_values='?', engine='c')

In [60]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
147,24.0,4,90.0,75.0,2108.0,15.5,74,2,fiat 128
287,16.5,8,351.0,138.0,3955.0,13.2,79,1,mercury grand marquis
261,18.1,6,258.0,120.0,3410.0,15.1,78,1,amc concord d/l
210,19.0,6,156.0,108.0,2930.0,15.5,76,3,toyota mark ii
279,29.5,4,98.0,68.0,2135.0,16.6,78,3,honda accord lx

In [61]:
 display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [62]:
 mpg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 28.1+ KB

### 3.2.2 Correlaciones entre valores

In [64]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg =- peso

np.float64(-0.8317409332443351)

In [65]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso =- aceleracion

np.float64(-0.4174573199403932)

### 3.2.3 Correlaciones entre todos los valores

In [66]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [67]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [70]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [71]:
print("matplotlib importado correctamente")
print(plt.__name__)

matplotlib importado correctamente
matplotlib.pyplot

In [72]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [73]:
 # correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: object

In [75]:
 # correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax() #consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: object

In [76]:
 # tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,0.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,0.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,0.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,0.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,0.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,0.000000

mpg                  aceleracion
cilindros         desplazamiento
desplazamiento         cilindros
potencia          desplazamiento
peso              desplazamiento
aceleracion                  mpg
dtype: object

In [78]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1,vmin=-1.0, vmax=1.0)

## 3.3 Ejercicios
Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandaspuzzles/blob/master/100-pandas-puzzles.ipynb